### ISSUE TITLE
Output is missing CSS classes

### ISSUE THREAD

**Issue by martinsiden** [scttcper/toastr-ng2#15]
Hello!

Thanks for this ng2 port of Toastr. 
Unfortunately, there seems to some kind of problem with the CSS selectors. 

An element with id "#toast-container" gets produced, but that element does not contain the actual toast, so the CSS selectors that looks like this:

`#toast-container .toast`

Doesn't work. The messages just appear on the middle of the screen with full width (only background color is set). If you add the specific types below that selector like this:

`#toast-container .toast,
.toast-success,
.toast-error,
.toast-info,
.toast-warning {
  ...`

The messages starts to look like they should. 
There must be something wrong with the markup and/or missing classes on the output?

**Comment by scttcper** [comment]
Here's what I'm seeing. The problem is probably the toast-component element from angular 2. I'll see if its possible to remove that. The component might have to become a directive or something. I'm not sure how that works in angular 2.
```html
<div class="overlay-container">
   <div id="toast-container" class="toast-top-right">
      <toast-component>
         <div class="toast toast-success" style="opacity: 1;">
            <div class="toast-title" aria-label="��">��</div>
            <div class="toast-message" aria-label="Rice bowls">
               Rice bowls
            </div>
         </div>
      </toast-component>
   </div>
</div>
```

**Comment by scttcper** [comment]
See if 1.4.0 fixes this for you https://github.com/scttcper/toastr-ng2/releases/tag/1.4.0

**Comment by martinsiden** [comment]
It does! Works wonderfully now. 

Thank you sir!
