### ISSUE TITLE
SCSS file in npm package?

### ISSUE THREAD

**Issue by dharapvj** [scttcper/toastr-ng2#17]
Hi,

Currently, if I try to use toastr-ng2 in angular2 project, I need to incorporate the SCSS file manually. Can the file be made part of npm package so that I can just include it out of node_modules?

Thanks for a quick port of toastr!

**Comment by scttcper** [comment]
Its css. I've renamed the file to match.
Released 1.4.3 with the css file `@import 'node_modules/toastr-ng2/toastr';` in your sass file should work.
