### ISSUE TITLE
allow html

### ISSUE THREAD

**Issue by scttcper** [scttcper/toastr-ng2#2]
allow html to be inserted into default toast component when enabled

**Comment by scttcper** [comment]
not doing this. easy to replace toast component

**Comment by OscarGalindo** [comment]
@scttcper can you explain this? i want to put html inside the toast

**Comment by scttcper** [comment]
@OscarGalindo you can check out the (pink toast in the demo)[https://github.com/scttcper/toastr-ng2/blob/master/src/app/pink.toast.ts]. 

It inherits the controller from the original toast and only replaces the aesthetics. You'll need to pass this component to the [individual toast options](https://github.com/scttcper/toastr-ng2#toastconfig-individual-toast-options) and it will need to be declared and an entry component in your module https://github.com/scttcper/toastr-ng2/blob/master/src/app/app.module.ts#L19

**Comment by scttcper** [comment]
You can also pass it as a global option when you setup the toastr
