### ISSUE TITLE
Toast not showing until click on layout when using with ng-bootstrap Modal

### ISSUE THREAD

**Issue by bergben** [scttcper/toastr-ng2#25]
Hey there.

I am using a modal from ng-bootstrap: https://ng-bootstrap.github.io/#/components/modal. When I create a toast while the modal is still open but in  the process of being closed using `this.toastrService.error('Error')` this toast does not show up until I click somewhere on the page. 
Maybe to explain it better:
The user enters information in the modal and clicks "Save". I do the update in the database, close the modal and want to show a toast "Saved" or "Error". 
Semi-pseudo-code:
```JavaScript
 updateToDatabase("value").subscribe((value)=>{
     closeModal();
     this.toastrService.success("Wheeeew it worked!");
});
```
The modal closes, the toast does not show up.
I click somewhere on the page (no matter where exactly) and the toast shows up. 
I also tried using 
`setTimeout(()=>{this.toastrService.success("Wheeew it worked!")},0)`

This seems a little odd to me so I figured it's best to just ask. 

Thanks for providing the module!

**Comment by scttcper** [comment]
I've tried it out: https://scttcper.github.io//toastbug//
src: https://github.com/scttcper/toastbug/blob/master/src/app/openmodal/openmodal.component.ts 

Not able to recreate it.

**Comment by bergben** [comment]
Hey @scttcper thanks for helping me out. 

I found out that the problem was, that I basically did:
```TypeScript
this.toastrService.success("Wheeew it worked!");
close();
```
whereas close was the passed on function to close the modal. 
When doing the following instead, all works fine:
```TypeScript
this.modalService.open(modal, { size: "lg", backdrop: "static" }).result.then((result) => {
      if(result && result.type){
        if(result.type==="error"){
           this.toastrService.error(result.message, 'Error!');
        }
        else if(result.type==="success"){
           this.toastrService.success(result.message, 'Saved!');
        }
      }
});
[...]
close({type:"success", mesage:"Wheeew it worked!"});
```
So for some reason the Toast has to be created in the modal.open.result callback, otherwise it won't work. I don't quite know why, but as long as there is a working solution it doesn't really matter I guess.

Thanks again.
