### ISSUE TITLE
newestOnTop global option seems to  be ignored when adding a Toast

### ISSUE THREAD

**Issue by rscrimo** [scttcper/toastr-ng2#26]
It seems that newestOnTop is being ignored with the latest updates for angular 2.2.0.  Just wanted to let you know so you can look into it.  I wish I had the time to investigate further but I am slammed right now.  I have tried your demo (https://scttcper.github.io/toastr-ng2/) and what I am seeing in my app is the same as the demo.

Thank you,
Robert

**Comment by rscrimo** [comment]
I am using toastr-ng v.2.0.1

**Comment by rscrimo** [comment]
BTW, thanks for all your work on this.  This is a great component and service.

**Comment by scttcper** [comment]
Hey thanks!
I believe its fixed in 2.0.2

**Comment by rscrimo** [comment]
Sure thing.  Thank you Scott.  I will give it a whirl.

Also, not sure if this is an issue, so I will ask and if so I can open another bug:
When extended timeout is 0 and the progress bar is enabled, if there is a bunch of auto dismiss toasts and you quickly run the mouse across them, some toasts can just disappear instead of what I think should happen, which is just to stop the auto dismiss (stick around).

Let me know if it is working as designed or I need to create a new bug.

Thank you,
Robert

**Comment by rscrimo** [comment]
Okay.  As far as I can tell it is fixed with 2.0.2.  Thanks a bunch.

**Comment by rscrimo** [comment]
I will create a new bug for the other possible issue and close this one since it is resolved.  If the other thing I am seeing is working as designed or not then we can deal with it on the other issue. Thanks Again.
