### ISSUE TITLE
some auto-dismiss toasts with extended timeout of 0 can just disappear when mouse quickly moves across them

### ISSUE THREAD

**Issue by rscrimo** [scttcper/toastr-ng2#27]
Also, not sure if this is an issue, so I will ask:
When extended timeout is 0 and the progress bar is enabled, if there is a bunch of auto dismiss toasts and you quickly run the mouse across them, some toasts can just disappear instead of what I think should happen, which is just to stop the auto dismiss (stick around).

This is not a huge deal to me but I thought you should know.

Thank you,
Robert

**Comment by scttcper** [comment]
fixed in 2.0.3

**Comment by rscrimo** [comment]
Confirmed that this is fixed on 2.0.3.
