### ISSUE TITLE
toastr inside a div

### ISSUE THREAD

**Issue by OscarGalindo** [scttcper/toastr-ng2#28]
It's possible to make the toastr appears inside a div instead of body?

**Comment by scttcper** [comment]
Can you clarify? I'm not sure what you mean.

**Comment by OscarGalindo** [comment]
Now is working like this:

body 
   my-app
   toastr

and i want something like this:

body
   my-app
       div
            toastr

**Comment by scttcper** [comment]
Currently, that's not possible. Is there a reason you'd be looking to do this? CSS?

**Comment by OscarGalindo** [comment]
yep, i have a part of the application exclusive for that kind of notifications and i want to show them inside

**Comment by scttcper** [comment]
I can work on adding this. angular/material overlay supports this but I deleted that bit of code.

**Comment by scttcper** [comment]
Released in 4.0

**Comment by OscarGalindo** [comment]
Perfect! I will update just now :-)
