### ISSUE TITLE
The toast UI element is not removed from the DOM after its removal

### ISSUE THREAD

**Issue by jemilg** [scttcper/toastr-ng2#30]
The toast UI element is not removed from the DOM after its removal, after the animation of the opacity is done the toastr component should remove the UI Element (div) from the dom, because its still clickable but not seen

**Comment by scttcper** [comment]
the toast-container? What element is sticking around?

**Comment by jemilg** [comment]
it wasn't an issue of this component (Toastr-ng2), i was registering the ToastrService multiple times, 1st was in the app module providers, and the 2nd was in the app home component providers.

This was creating a different ToastrService instances, the one that is registering viewContainerRef was different than the instance from which i show the toast
