### ISSUE TITLE
Library not AoT compatible

### ISSUE THREAD

**Issue by yarrgh** [scttcper/toastr-ng2#32]
Since version beta.22 of angular-cli, this library causes issues with compiling/building projects built with the CLI. I guess they (the Angular team) have determined that it is best to always use AoT compatible code/libraries even if AoT is not going to be used.

See this comment: [https://github.com/angular/angular-cli/issues/3368#issuecomment-265232700](https://github.com/angular/angular-cli/issues/3368#issuecomment-265232700) for more information.

You can see [https://angular.io/docs/ts/latest/cookbook/aot-compiler.html](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) for information on making it AoT compatible.

**Comment by scttcper** [comment]
what version of toastr-ng2 are you using?

**Comment by yarrgh** [comment]
Using version 2.0.4

**Comment by yarrgh** [comment]
Just realized that it is because I'm trying to override the toastr config globally. The following code causes the error:
`@NgModule({
  bootstrap: [App],
  declarations: [App],
  // Import Toastr!
  imports: [ ToastrModule ],
  providers: [
    // Override options here
    provideToastr({
      timeOut: 500,
    })
  ]
})`

Removing the function causes the project to build. Is there another way of setting the toastr config globally?

**Comment by scttcper** [comment]
Go ahead and give version 3 a try with the new method of setting global options. https://github.com/scttcper/toastr-ng2#override-default-settings

I don't like it as much but it seems like this is how most packages are doing it.

**Comment by yarrgh** [comment]
Yeah that seems to be working. Not as elegant but does the job neatly enough.

**Comment by scttcper** [comment]
Woo! 👍

**Comment by MrTimms** [comment]
I've updated to toastr 3.0.1 but I still have an AoT issue. (I'm using angular-cli 1.0.0-beta.22-1 to run _ng build --aot_)

ERROR in ./src/~/toastr-ng2/toast-component.ngfactory.ts
Module build failed: Error: C:/src/node_modules/toastr-ng2/toast-component.ngfactory.ts (54,40): Property 'toastClasses' is private and only accessible within class 'Toast'.)

**Comment by TianCNCA** [comment]
Same here. Please fix it.

**Comment by scttcper** [comment]
@TianCNCA @MrTimms i'm not getting that error but i've published 3.1.1 with toastClasses as public. Let me know if that fixes it for you.

**Comment by MrTimms** [comment]
@scttcper The compilation error is gone and it working fine for me. Thanks for the quick response.

**Comment by TianCNCA** [comment]
I'll test it some time later but yeah thanks for the quick response @scttcper
