### ISSUE TITLE
Error: Cannot read property 'Toast' of undefined

### ISSUE THREAD

**Issue by aslubsky** [scttcper/toastr-ng2#40]
"@angular": "2.3.1",
"toastr-ng2": "^3.2.1"

AOT + Rollup
Please clone my test repo https://github.com/aslubsky/toastr-ng2-aot-bug
`npm install`
`npm run build`

**Comment by yarrgh** [comment]
Is there supposed to be an error when running `npm run build`? If so I'm not seeing it.

**Comment by yarrgh** [comment]
Happens when trying to create the ToastConfig specifially when trying to assign value to the toastComponent.

When compiled with rollup it produces this javascript code:
```javascript
var ToastConfig$1 = (function () {
    function ToastConfig(config) {
        if (config === void 0) { config = {}; }
        // shows close button
        this.closeButton = false;
        this.extendedTimeOut = 1000;
        this.onHidden = new core_1$3.EventEmitter();
        this.onShown = new core_1$3.EventEmitter();
        this.onTap = new core_1$3.EventEmitter();
        this.progressBar = false;
        this.timeOut = 5000;
        this.toastClass = 'toast';
        this.positionClass = 'toast-top-right';
        this.titleClass = 'toast-title';
        this.messageClass = 'toast-message';
        this.tapToDismiss = true;
        this.toastComponent = toast_component_1$1.Toast; // happens here
        // ... the rest of the code...
```
Produces `TypeError: Cannot read property 'Toast' of undefined`

I'm not familiar enough with rollup yet so I'm wondering why this happens with rollup and not angular-cli when using AoT.

**Comment by aslubsky** [comment]
Sorry, we have a different time zone. Thanks for your work and time. I have come to the same conclusion, but can't switch from rollup to webpack for now. I will research this bug more deep

**Comment by scttcper** [comment]
Released 3.2.2 to address this. You should delete the rollup code that imports as common js and it should work.

**Comment by scttcper** [comment]
@yarrgh if you get a chance can you try 3.2.2. I'm getting weird results. Also they unpublished angular-cli 32 or something is wrong with npm.

**Comment by aslubsky** [comment]
Thanks a lot!

**Comment by yarrgh** [comment]
@scttcper What weird results are you seeing?

**Comment by scttcper** [comment]
@yarrgh my project was getting stuck at 70%. Turns out it was a node-sass issue from rolling back to 21-1 since 23 wasn't available. Very frustrating to figure out with no errors.
