### ISSUE TITLE
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

### ISSUE THREAD

**Issue by phmello** [scttcper/toastr-ng2#51]
Im getting the following error when trying to lazy load a module

Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by phmello** [comment]
I was trying to import the ToastrModule on a sub module, importing on the AppModule works fine

**Comment by scttcper** [comment]
I don't see any issue with removing browser module since we have common module. I've added this to the v4 pr #50
