### ISSUE TITLE
Toaster visible only on next user click

### ISSUE THREAD

**Issue by olaf89** [scttcper/toastr-ng2#53]
I have an issue, when toaster is supposed to be added by background stream its not being displayed until screen is clicked.
So in order for it to become visible i need to do 
setTimeout(_ => { window.document.body.click(); }, 1 );

Is there a better way to run change detection for this component? or maybe i should configure it somehow.

**Comment by scttcper** [comment]
What do you mean by background stream?

**Comment by olaf89** [comment]
My actual case is rxjs stream created from websocket events, meaning no user interaction with UI.

**Comment by yarrgh** [comment]
You could try injecting ChangeDetectorRef into your service/component and mannually trigger a change detection using the detectChanges() method.

See https://angular.io/docs/ts/latest/api/core/index/ChangeDetectorRef-class.html

**Comment by olaf89** [comment]
That was first thing i tried, and would be an acceptable solution as well. Yet it does not seem to work.

**Comment by yarrgh** [comment]
Might not be working because ChangeDetectorRef.detectChanges() only triggers change detection in the local component (and it's children).

Have you tried ApplicationRef.tick()? ([docs](https://angular.io/docs/ts/latest/api/core/index/ApplicationRef-class.html#!#tick-anchor))

It's suppose to trigger a full change detection for the whole application if I'm understanding the docs correctly.

**Comment by olaf89** [comment]
It works when you detect changes after onShown.
`  toast.onShown.first().subscribe(_ => this.appRef.tick());`
Thats much better then initial solution. Thanks :)

**Comment by yarrgh** [comment]
Might be able to do something where we add another configuration flag or something where when the toast is displayed and the flag is set, we trigger a change detection within the component. What do you think @scttcper

**Comment by scttcper** [comment]
sounds good to me.

Maybe here? https://github.com/scttcper/toastr-ng2/blob/master/src/lib/toast-injector.ts#L35

or would putting it into the toast itself make sense?

**Comment by yarrgh** [comment]
It would probably be best if it can be within the component itself. Then you can use `ChangeDetectorRef.detectChanges()` to only trigger change detection within the component. Probably somewhere [here](https://github.com/scttcper/toastr-ng2/blob/master/src/lib/toast-component.ts#L100). I'm hoping that this will be enough to allow the toast to show. Might have to have @olaf89 test for use unless you know how to duplicate his scenario.

**Comment by olaf89** [comment]
If you prepare any solution Im happy to test that, just let me know.

**Comment by scttcper** [comment]
I committed straight on master like a terrible person.

https://github.com/scttcper/toastr-ng2/commit/ceccaf73a0e83455a4ec0705b5e989f55fbd3f16 has the changes. See if turning on onActivateTick works.

**Comment by olaf89** [comment]
I tried it and it solves the issue, thanks!
