### ISSUE TITLE
onTap setup

### ISSUE THREAD

**Issue by andrewsafwat** [scttcper/toastr-ng2#60]
Can you please tell me how to call a function when click on a toastr?
and if it by using onTap, can you tell me an example.

Thanks in advance.

**Comment by scttcper** [comment]
onTap is an observable passed back from creating the toast.
```typescript
const toast = this.toastrService.success('toast')
toast.onTap.subscribe(() => {
  console.log('clicked')
})
```

**Comment by andrewsafwat** [comment]
Thanks a lot
