### ISSUE TITLE
Overriding options based on toast type

### ISSUE THREAD

**Issue by wolfhoundjesse** [scttcper/toastr-ng2#7]
Currently options are passed by reference. E.g., if I want to have success toasts time out and error toasts remain, passing options for one will change the other. 

Then again, this might be one of those times where I think I know what I'm talking about, but I'm just missing something.

**Comment by scttcper** [comment]
Each toast is aware of its own time to live when created. Easiest way is to set the default config and a custom config for the other toast. 

Let me know if this works for you.
```javascript
import { ToastConfig } from 'toastr-ng2';

let errorConfig = new ToastConfig();
errorConfig.timeOut = 0;
this.toastService.error('everything is broken', 'title is optional', errorConfig);
```

**Comment by wolfhoundjesse** [comment]
I tested this with timeout, and it worked. I think the issue is that I tested it with positionClass, trying to get the different toasts to show up in different places. That is an entirely different issue. Thanks for your help!

**Comment by scttcper** [comment]
Currently only one positionClass can be used at a time since its set at the container level. Once the toasts expire or are cleared, another container will be created with whatever the positionClass is set to. This is the same way angular-toastr and original toastr work.
